resolver: lts-7.17
packages:
  - highjson
  - highjson-swagger
  - location:
      git: https://github.com/agrafix/hvect.git
      commit: 06ed63c1efbcd53aaf786f7b00ea0d852a11f901
    extra-dep: true
extra-deps:
  - aeson-1.1.0.0
  - swagger2-2.1.3
  - insert-ordered-containers-0.2.0.0
